#!/bin/bash
BIN=main.o
REMOTE=/mnt/ufs/app/Nucleus/$BIN
OPT="-DLV_CONF_PATH="\"../lv_conf.h\"" -DLV_LVGL_H_INCLUDE_SYSTEM -DLV_LVGL_H_INCLUDE_SIMPLE -I. -std=gnu99"
GCC=/home/user/Desktop/sunyard/sunyard-tools/le_arm11_external_20090506/bin/arm-brcm-linux-gnueabi-gcc
$GCC $OPT main.c -L. -llvgl -L/home/user/Desktop/sunyard/FNlib/lib/ -lsdk -lapi -o $BIN
echo -e "user anonymous anonymous\ndel $REMOTE\nput $BIN $REMOTE" | ftp -p -n 10.42.0.140
exit 0
$GCC -shared -o liblvgl.so $OPT -lpthread -lm \
./demos/gltf/lv_demo_gltf.c \
./demos/render/lv_demo_render.c \
./demos/render/assets/img_render_lvgl_logo_l8.c \
./demos/render/assets/img_render_lvgl_logo_rgb888.c \
./demos/render/assets/img_render_lvgl_logo_i1.c \
./demos/render/assets/img_render_lvgl_logo_rgb565_swapped.c \
./demos/render/assets/img_render_lvgl_logo_xrgb8888.c \
./demos/render/assets/img_render_lvgl_logo_argb8888_premultiplied.c \
./demos/render/assets/img_render_arc_bg.c \
./demos/render/assets/img_render_lvgl_logo_rgb565a8.c \
./demos/render/assets/img_render_lvgl_logo_argb8888.c \
./demos/render/assets/img_render_lvgl_logo_rgb565.c \
./demos/vector_graphic/assets/img_demo_vector_avatar.c \
./demos/vector_graphic/lv_demo_vector_graphic.c \
./demos/music/lv_demo_music_main.c \
./demos/music/lv_demo_music.c \
./demos/music/assets/img_lv_demo_music_cover_2.c \
./demos/music/assets/img_lv_demo_music_slider_knob_large.c \
./demos/music/assets/img_lv_demo_music_cover_3.c \
./demos/music/assets/img_lv_demo_music_icon_4.c \
./demos/music/assets/img_lv_demo_music_btn_loop.c \
./demos/music/assets/img_lv_demo_music_wave_top.c \
./demos/music/assets/img_lv_demo_music_btn_prev_large.c \
./demos/music/assets/img_lv_demo_music_slider_knob.c \
./demos/music/assets/img_lv_demo_music_btn_play.c \
./demos/music/assets/img_lv_demo_music_btn_list_pause.c \
./demos/music/assets/img_lv_demo_music_list_border.c \
./demos/music/assets/img_lv_demo_music_corner_left_large.c \
./demos/music/assets/img_lv_demo_music_icon_1_large.c \
./demos/music/assets/img_lv_demo_music_btn_loop_large.c \
./demos/music/assets/img_lv_demo_music_wave_bottom.c \
./demos/music/assets/img_lv_demo_music_icon_3_large.c \
./demos/music/assets/img_lv_demo_music_btn_rnd_large.c \
./demos/music/assets/img_lv_demo_music_btn_play_large.c \
./demos/music/assets/img_lv_demo_music_list_border_large.c \
./demos/music/assets/img_lv_demo_music_cover_2_large.c \
./demos/music/assets/img_lv_demo_music_btn_corner_large.c \
./demos/music/assets/img_lv_demo_music_btn_rnd.c \
./demos/music/assets/img_lv_demo_music_corner_right_large.c \
./demos/music/assets/img_lv_demo_music_btn_pause_large.c \
./demos/music/assets/img_lv_demo_music_icon_3.c \
./demos/music/assets/img_lv_demo_music_cover_1.c \
./demos/music/assets/img_lv_demo_music_logo.c \
./demos/music/assets/img_lv_demo_music_icon_2_large.c \
./demos/music/assets/img_lv_demo_music_cover_3_large.c \
./demos/music/assets/img_lv_demo_music_btn_list_pause_large.c \
./demos/music/assets/img_lv_demo_music_wave_bottom_large.c \
./demos/music/assets/img_lv_demo_music_icon_4_large.c \
./demos/music/assets/img_lv_demo_music_wave_top_large.c \
./demos/music/assets/img_lv_demo_music_corner_right.c \
./demos/music/assets/img_lv_demo_music_icon_2.c \
./demos/music/assets/img_lv_demo_music_btn_pause.c \
./demos/music/assets/img_lv_demo_music_btn_list_play.c \
./demos/music/assets/img_lv_demo_music_cover_1_large.c \
./demos/music/assets/img_lv_demo_music_icon_1.c \
./demos/music/assets/img_lv_demo_music_btn_next.c \
./demos/music/assets/img_lv_demo_music_btn_list_play_large.c \
./demos/music/assets/img_lv_demo_music_corner_left.c \
./demos/music/assets/img_lv_demo_music_btn_prev.c \
./demos/music/assets/img_lv_demo_music_btn_next_large.c \
./demos/music/lv_demo_music_list.c \
./demos/widgets/lv_demo_widgets_shop.c \
./demos/widgets/lv_demo_widgets_analytics.c \
./demos/widgets/lv_demo_widgets_profile.c \
./demos/widgets/lv_demo_widgets_components.c \
./demos/widgets/assets/img_clothes.c \
./demos/widgets/assets/img_demo_widgets_avatar.c \
./demos/widgets/assets/img_lvgl_logo.c \
./demos/widgets/assets/img_demo_widgets_needle.c \
./demos/widgets/lv_demo_widgets.c \
./demos/stress/lv_demo_stress.c \
./demos/benchmark/lv_demo_benchmark.c \
./demos/benchmark/assets/img_benchmark_lvgl_logo_argb.c \
./demos/benchmark/assets/lv_font_benchmark_montserrat_14_aligned.c \
./demos/benchmark/assets/lv_font_benchmark_montserrat_12_aligned.c \
./demos/benchmark/assets/lv_font_benchmark_montserrat_26_aligned.c \
./demos/benchmark/assets/lv_font_benchmark_montserrat_18_aligned.c \
./demos/benchmark/assets/lv_font_benchmark_montserrat_16_aligned.c \
./demos/benchmark/assets/lv_font_benchmark_montserrat_24_aligned.c \
./demos/benchmark/assets/img_benchmark_lvgl_logo_rgb.c \
./demos/benchmark/assets/lv_font_benchmark_montserrat_20_aligned.c \
./demos/benchmark/assets/img_benchmark_avatar.c \
./demos/keypad_encoder/lv_demo_keypad_encoder.c \
./demos/lv_demos.c \
./src/core/lv_obj.c \
./src/core/lv_obj_tree.c \
./src/core/lv_obj_scroll.c \
./src/core/lv_obj_property.c \
./src/core/lv_obj_draw.c \
./src/core/lv_obj_id_builtin.c \
./src/core/lv_obj_style_gen.c \
./src/core/lv_refr.c \
./src/core/lv_obj_class.c \
./src/core/lv_obj_pos.c \
./src/core/lv_group.c \
./src/core/lv_obj_style.c \
./src/core/lv_obj_event.c \
./src/core/lv_observer.c \
./src/drivers/sdl/lv_sdl_mousewheel.c \
./src/drivers/sdl/lv_sdl_keyboard.c \
./src/drivers/sdl/lv_sdl_window.c \
./src/drivers/sdl/lv_sdl_texture.c \
./src/drivers/sdl/lv_sdl_egl.c \
./src/drivers/sdl/lv_sdl_mouse.c \
./src/drivers/sdl/lv_sdl_sw.c \
./src/drivers/libinput/lv_libinput.c \
./src/drivers/libinput/lv_xkb.c \
./src/drivers/opengles/glad/src/egl.c \
./src/drivers/opengles/glad/src/gl.c \
./src/drivers/opengles/glad/src/gles2.c \
./src/drivers/opengles/lv_opengles_debug.c \
./src/drivers/opengles/lv_opengles_glfw.c \
./src/drivers/opengles/lv_opengles_texture.c \
./src/drivers/opengles/opengl_shader/lv_opengl_shader_program.c \
./src/drivers/opengles/opengl_shader/lv_opengl_shader_manager.c \
./src/drivers/opengles/lv_opengles_egl.c \
./src/drivers/opengles/lv_opengles_driver.c \
./src/drivers/opengles/assets/lv_opengles_shader.c \
./src/drivers/windows/lv_windows_input.c \
./src/drivers/windows/lv_windows_display.c \
./src/drivers/windows/lv_windows_context.c \
./src/drivers/nuttx/lv_nuttx_touchscreen.c \
./src/drivers/nuttx/lv_nuttx_lcd.c \
./src/drivers/nuttx/lv_nuttx_cache.c \
./src/drivers/nuttx/lv_nuttx_libuv.c \
./src/drivers/nuttx/lv_nuttx_profiler.c \
./src/drivers/nuttx/lv_nuttx_fbdev.c \
./src/drivers/nuttx/lv_nuttx_mouse.c \
./src/drivers/nuttx/lv_nuttx_entry.c \
./src/drivers/nuttx/lv_nuttx_image_cache.c \
./src/drivers/wayland/lv_wayland.c \
./src/drivers/wayland/lv_wayland_touch.c \
./src/drivers/wayland/lv_wayland_seat.c \
./src/drivers/wayland/lv_wayland_xdg_shell.c \
./src/drivers/wayland/lv_wayland_keyboard.c \
./src/drivers/wayland/lv_wayland_backend_egl.c \
./src/drivers/wayland/lv_wayland_backend_g2d.c \
./src/drivers/wayland/lv_wayland_pointer.c \
./src/drivers/wayland/lv_wayland_window.c \
./src/drivers/wayland/lv_wayland_backend_shm.c \
./src/drivers/x11/lv_x11_input.c \
./src/drivers/x11/lv_x11_display.c \
./src/drivers/evdev/lv_evdev.c \
./src/drivers/draw/eve/lv_draw_eve_display.c \
./src/drivers/display/drm/lv_linux_drm_egl.c \
./src/drivers/display/drm/lv_linux_drm_common.c \
./src/drivers/display/drm/lv_linux_drm.c \
./src/drivers/display/st7735/lv_st7735.c \
./src/drivers/display/nv3007/lv_nv3007.c \
./src/drivers/display/ili9341/lv_ili9341.c \
./src/drivers/display/nxp_elcdif/lv_nxp_elcdif.c \
./src/drivers/display/ft81x/lv_ft81x.c \
./src/drivers/display/fb/lv_linux_fbdev.c \
./src/drivers/display/st7796/lv_st7796.c \
./src/drivers/display/lcd/lv_lcd_generic_mipi.c \
./src/drivers/display/st7789/lv_st7789.c \
./src/drivers/display/st_ltdc/lv_st_ltdc.c \
./src/drivers/display/renesas_glcdc/lv_renesas_glcdc.c \
./src/drivers/qnx/lv_qnx.c \
./src/drivers/uefi/lv_uefi_indev_touch.c \
./src/drivers/uefi/lv_uefi_indev_pointer.c \
./src/drivers/uefi/lv_uefi_context.c \
./src/drivers/uefi/lv_uefi_indev_keyboard.c \
./src/drivers/uefi/lv_uefi_display.c \
./src/drivers/uefi/lv_uefi_private.c \
./src/osal/lv_sdl2.c \
./src/osal/lv_rtthread.c \
./src/osal/lv_cmsis_rtos2.c \
./src/osal/lv_os.c \
./src/osal/lv_pthread.c \
./src/osal/lv_windows.c \
./src/osal/lv_linux.c \
./src/osal/lv_freertos.c \
./src/osal/lv_os_none.c \
./src/osal/lv_mqx.c \
./src/others/file_explorer/lv_file_explorer.c \
./src/others/translation/lv_translation.c \
./src/others/fragment/lv_fragment_manager.c \
./src/others/fragment/lv_fragment.c \
./src/misc/lv_ll.c \
./src/misc/lv_array.c \
./src/misc/lv_async.c \
./src/misc/lv_area.c \
./src/misc/lv_log.c \
./src/misc/lv_pending.c \
./src/misc/lv_timer.c \
./src/misc/lv_templ.c \
./src/misc/lv_palette.c \
./src/misc/lv_utils.c \
./src/misc/cache/instance/lv_image_cache.c \
./src/misc/cache/instance/lv_image_header_cache.c \
./src/misc/cache/class/lv_cache_sc_da.c \
./src/misc/cache/class/lv_cache_lru_ll.c \
./src/misc/cache/class/lv_cache_lru_rb.c \
./src/misc/cache/lv_cache.c \
./src/misc/cache/lv_cache_entry.c \
./src/misc/lv_anim_timeline.c \
./src/misc/lv_grad.c \
./src/misc/lv_style.c \
./src/misc/lv_math.c \
./src/misc/lv_fs.c \
./src/misc/lv_iter.c \
./src/misc/lv_anim.c \
./src/misc/lv_tree.c \
./src/misc/lv_color.c \
./src/misc/lv_event.c \
./src/misc/lv_lru.c \
./src/misc/lv_bidi.c \
./src/misc/lv_circle_buf.c \
./src/misc/lv_profiler_builtin.c \
./src/misc/lv_profiler_builtin_posix.c \
./src/misc/lv_text.c \
./src/misc/lv_style_gen.c \
./src/misc/lv_color_op.c \
./src/misc/lv_rb.c \
./src/misc/lv_matrix.c \
./src/misc/lv_text_ap.c \
./src/font/lv_font_montserrat_46.c \
./src/font/lv_font_montserrat_16.c \
./src/font/lv_font_montserrat_18.c \
./src/font/lv_font_montserrat_36.c \
./src/font/lv_font_montserrat_32.c \
./src/font/font_manager/lv_font_manager.c \
./src/font/font_manager/lv_font_manager_recycle.c \
./src/font/lv_font_montserrat_42.c \
./src/font/lv_font_montserrat_20.c \
./src/font/lv_font_montserrat_40.c \
./src/font/lv_font_montserrat_22.c \
./src/font/lv_font_dejavu_16_persian_hebrew.c \
./src/font/lv_font_montserrat_10.c \
./src/font/lv_font_source_han_sans_sc_16_cjk.c \
./src/font/lv_font.c \
./src/font/lv_font_montserrat_48.c \
./src/font/lv_font_montserrat_12.c \
./src/font/imgfont/lv_imgfont.c \
./src/font/lv_font_montserrat_14_aligned.c \
./src/font/lv_font_source_han_sans_sc_14_cjk.c \
./src/font/fmt_txt/lv_font_fmt_txt.c \
./src/font/lv_font_montserrat_14.c \
./src/font/lv_font_montserrat_28_compressed.c \
./src/font/lv_font_montserrat_26.c \
./src/font/lv_font_montserrat_8.c \
./src/font/lv_font_montserrat_44.c \
./src/font/lv_font_montserrat_38.c \
./src/font/lv_font_montserrat_28.c \
./src/font/lv_font_montserrat_30.c \
./src/font/lv_font_unscii_16.c \
./src/font/lv_font_unscii_8.c \
./src/font/lv_font_montserrat_34.c \
./src/font/lv_font_montserrat_24.c \
./src/font/binfont_loader/lv_binfont_loader.c \
./src/libs/tjpgd/lv_tjpgd.c \
./src/libs/tjpgd/tjpgd.c \
./src/libs/qrcode/lv_qrcode.c \
./src/libs/qrcode/qrcodegen.c \
./src/libs/frogfs/src/decomp_raw.c \
./src/libs/frogfs/src/frogfs.c \
./src/libs/lz4/lz4.c \
./src/libs/gltf/gltf_environment/lv_gltf_ibl_sampler.c \
./src/libs/gltf/gltf_view/assets/chromatic.c \
./src/libs/gltf/gltf_view/assets/lv_gltf_view_shader.c \
./src/libs/gltf/math/lv_3dmath.c \
./src/libs/gltf/gltf_data/lv_gltf_model_loader.c \
./src/libs/libwebp/lv_libwebp.c \
./src/libs/ffmpeg/lv_ffmpeg.c \
./src/libs/rle/lv_rle.c \
./src/libs/bmp/lv_bmp.c \
./src/libs/tiny_ttf/lv_tiny_ttf.c \
./src/libs/nanovg/nanovg.c \
./src/libs/gif/gif.c \
./src/libs/fsdrv/lv_fs_stdio.c \
./src/libs/fsdrv/lv_fs_posix.c \
./src/libs/fsdrv/lv_fs_memfs.c \
./src/libs/fsdrv/lv_fs_fatfs.c \
./src/libs/fsdrv/lv_fs_littlefs.c \
./src/libs/fsdrv/lv_fs_cbfs.c \
./src/libs/fsdrv/lv_fs_uefi.c \
./src/libs/fsdrv/lv_fs_win32.c \
./src/libs/fsdrv/lv_fs_frogfs.c \
./src/libs/FT800-FT813/EVE_commands.c \
./src/libs/FT800-FT813/EVE_supplemental.c \
./src/libs/gstreamer/lv_gstreamer.c \
./src/libs/bin_decoder/lv_bin_decoder.c \
./src/libs/barcode/code128.c \
./src/libs/barcode/lv_barcode.c \
./src/libs/libjpeg_turbo/lv_libjpeg_turbo.c \
./src/libs/libpng/lv_libpng.c \
./src/libs/lodepng/lodepng.c \
./src/libs/lodepng/lv_lodepng.c \
./src/libs/vg_lite_driver/VGLite/vg_lite_matrix.c \
./src/libs/vg_lite_driver/VGLite/vg_lite_path.c \
./src/libs/vg_lite_driver/VGLite/vg_lite_stroke.c \
./src/libs/vg_lite_driver/VGLite/vg_lite.c \
./src/libs/vg_lite_driver/VGLite/vg_lite_image.c \
./src/libs/vg_lite_driver/VGLiteKernel/vg_lite_kernel.c \
./src/libs/vg_lite_driver/lv_vg_lite_hal/lv_vg_lite_hal.c \
./src/libs/vg_lite_driver/lv_vg_lite_hal/vg_lite_os.c \
./src/libs/freetype/lv_freetype_outline.c \
./src/libs/freetype/lv_freetype.c \
./src/libs/freetype/lv_freetype_image.c \
./src/libs/freetype/lv_freetype_glyph.c \
./src/libs/freetype/lv_ftsystem.c \
./src/libs/rlottie/lv_rlottie.c \
./src/libs/svg/lv_svg_render.c \
./src/libs/svg/lv_svg_token.c \
./src/libs/svg/lv_svg.c \
./src/libs/svg/lv_svg_parser.c \
./src/libs/svg/lv_svg_decoder.c \
./src/lv_init.c \
./src/layouts/grid/lv_grid.c \
./src/layouts/flex/lv_flex.c \
./src/layouts/lv_layout.c \
./src/widgets/animimage/lv_animimage.c \
./src/widgets/arc/lv_arc.c \
./src/widgets/objx_templ/lv_objx_templ.c \
./src/widgets/tabview/lv_tabview.c \
./src/widgets/label/lv_label.c \
./src/widgets/arclabel/lv_arclabel.c \
./src/widgets/3dtexture/lv_3dtexture.c \
./src/widgets/canvas/lv_canvas.c \
./src/widgets/switch/lv_switch.c \
./src/widgets/gif/lv_gif.c \
./src/widgets/image/lv_image.c \
./src/widgets/spinner/lv_spinner.c \
./src/widgets/menu/lv_menu.c \
./src/widgets/calendar/lv_calendar_chinese.c \
./src/widgets/calendar/lv_calendar_header_dropdown.c \
./src/widgets/calendar/lv_calendar.c \
./src/widgets/calendar/lv_calendar_header_arrow.c \
./src/widgets/property/lv_arc_properties.c \
./src/widgets/property/lv_dropdown_properties.c \
./src/widgets/property/lv_menu_properties.c \
./src/widgets/property/lv_scale_properties.c \
./src/widgets/property/lv_table_properties.c \
./src/widgets/property/lv_span_properties.c \
./src/widgets/property/lv_spinner_properties.c \
./src/widgets/property/lv_image_properties.c \
./src/widgets/property/lv_label_properties.c \
./src/widgets/property/lv_switch_properties.c \
./src/widgets/property/lv_chart_properties.c \
./src/widgets/property/lv_animimage_properties.c \
./src/widgets/property/lv_roller_properties.c \
./src/widgets/property/lv_style_properties.c \
./src/widgets/property/lv_buttonmatrix_properties.c \
./src/widgets/property/lv_slider_properties.c \
./src/widgets/property/lv_spinbox_properties.c \
./src/widgets/property/lv_led_properties.c \
./src/widgets/property/lv_tabview_properties.c \
./src/widgets/property/lv_checkbox_properties.c \
./src/widgets/property/lv_bar_properties.c \
./src/widgets/property/lv_line_properties.c \
./src/widgets/property/lv_obj_properties.c \
./src/widgets/property/lv_textarea_properties.c \
./src/widgets/property/lv_keyboard_properties.c \
./src/widgets/list/lv_list.c \
./src/widgets/checkbox/lv_checkbox.c \
./src/widgets/win/lv_win.c \
./src/widgets/dropdown/lv_dropdown.c \
./src/widgets/keyboard/lv_keyboard.c \
./src/widgets/lottie/lv_lottie.c \
./src/widgets/bar/lv_bar.c \
./src/widgets/tileview/lv_tileview.c \
./src/widgets/span/lv_span.c \
./src/widgets/table/lv_table.c \
./src/widgets/roller/lv_roller.c \
./src/widgets/chart/lv_chart.c \
./src/widgets/textarea/lv_textarea.c \
./src/widgets/ime/lv_ime_pinyin.c \
./src/widgets/scale/lv_scale.c \
./src/widgets/line/lv_line.c \
./src/widgets/imagebutton/lv_imagebutton.c \
./src/widgets/button/lv_button.c \
./src/widgets/led/lv_led.c \
./src/widgets/buttonmatrix/lv_buttonmatrix.c \
./src/widgets/slider/lv_slider.c \
./src/widgets/msgbox/lv_msgbox.c \
./src/widgets/spinbox/lv_spinbox.c \
./src/draw/sdl/lv_draw_sdl.c \
./src/draw/lv_draw_mask.c \
./src/draw/sw/lv_draw_sw_mask.c \
./src/draw/sw/lv_draw_sw_transform.c \
./src/draw/sw/lv_draw_sw_mask_rect.c \
./src/draw/sw/lv_draw_sw_utils.c \
./src/draw/sw/lv_draw_sw_arc.c \
./src/draw/sw/lv_draw_sw_blur.c \
./src/draw/sw/lv_draw_sw.c \
./src/draw/sw/lv_draw_sw_line.c \
./src/draw/sw/lv_draw_sw_letter.c \
./src/draw/sw/lv_draw_sw_triangle.c \
./src/draw/sw/lv_draw_sw_box_shadow.c \
./src/draw/sw/lv_draw_sw_fill.c \
./src/draw/sw/lv_draw_sw_grad.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_al88.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_i1.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_rgb565_swapped.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_rgb565.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_rgb888.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_a8.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_argb8888.c \
./src/draw/sw/blend/riscv_v/lv_draw_sw_blend_riscv_v_to_rgb888.c \
./src/draw/sw/blend/lv_draw_sw_blend.c \
./src/draw/sw/blend/neon/lv_draw_sw_blend_neon_to_rgb888.c \
./src/draw/sw/blend/neon/lv_draw_sw_blend_neon_to_rgb565.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_argb8888_premultiplied.c \
./src/draw/sw/blend/lv_draw_sw_blend_to_l8.c \
./src/draw/sw/lv_draw_sw_border.c \
./src/draw/sw/lv_draw_sw_img.c \
./src/draw/sw/lv_draw_sw_vector.c \
./src/draw/lv_draw_vector.c \
./src/draw/lv_draw_buf.c \
./src/draw/lv_draw_arc.c \
./src/draw/opengles/lv_draw_opengles.c \
./src/draw/nanovg/lv_draw_nanovg_line.c \
./src/draw/nanovg/lv_draw_nanovg_vector.c \
./src/draw/nanovg/lv_draw_nanovg_box_shadow.c \
./src/draw/nanovg/lv_draw_nanovg.c \
./src/draw/nanovg/lv_draw_nanovg_fill.c \
./src/draw/nanovg/lv_draw_nanovg_mask_rect.c \
./src/draw/nanovg/lv_draw_nanovg_image.c \
./src/draw/nanovg/lv_draw_nanovg_border.c \
./src/draw/nanovg/lv_draw_nanovg_triangle.c \
./src/draw/nanovg/lv_nanovg_fbo_cache.c \
./src/draw/nanovg/lv_draw_nanovg_arc.c \
./src/draw/nanovg/lv_nanovg_image_cache.c \
./src/draw/nanovg/lv_nanovg_utils.c \
./src/draw/nanovg/lv_draw_nanovg_layer.c \
./src/draw/nanovg/lv_draw_nanovg_grad.c \
./src/draw/nanovg/lv_draw_nanovg_3d.c \
./src/draw/nanovg/lv_draw_nanovg_label.c \
./src/draw/lv_draw_3d.c \
./src/draw/lv_draw_image.c \
./src/draw/snapshot/lv_snapshot.c \
./src/draw/lv_draw_triangle.c \
./src/draw/lv_draw.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_fill.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_layer.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_img.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_arc.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_stm32_hal.c \
./src/draw/nema_gfx/lv_nema_gfx_path.c \
./src/draw/nema_gfx/lv_draw_nema_gfx.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_utils.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_triangle.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_border.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_vector.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_line.c \
./src/draw/nema_gfx/lv_draw_nema_gfx_label.c \
./src/draw/lv_draw_line.c \
./src/draw/lv_draw_blur.c \
./src/draw/espressif/ppa/lv_draw_ppa_fill.c \
./src/draw/espressif/ppa/lv_draw_ppa_buf.c \
./src/draw/espressif/ppa/lv_draw_ppa.c \
./src/draw/espressif/ppa/lv_draw_ppa_img.c \
./src/draw/lv_image_decoder.c \
./src/draw/nxp/g2d/lv_g2d_utils.c \
./src/draw/nxp/g2d/lv_draw_g2d.c \
./src/draw/nxp/g2d/lv_g2d_buf_map.c \
./src/draw/nxp/g2d/lv_draw_buf_g2d.c \
./src/draw/nxp/g2d/lv_draw_g2d_img.c \
./src/draw/nxp/g2d/lv_draw_g2d_fill.c \
./src/draw/nxp/pxp/lv_pxp_cfg.c \
./src/draw/nxp/pxp/lv_draw_pxp_img.c \
./src/draw/nxp/pxp/lv_draw_pxp_fill.c \
./src/draw/nxp/pxp/lv_pxp_utils.c \
./src/draw/nxp/pxp/lv_draw_pxp.c \
./src/draw/nxp/pxp/lv_draw_pxp_layer.c \
./src/draw/nxp/pxp/lv_pxp_osa.c \
./src/draw/nxp/pxp/lv_draw_buf_pxp.c \
./src/draw/convert/helium/lv_draw_buf_convert_helium.c \
./src/draw/convert/lv_draw_buf_convert.c \
./src/draw/convert/neon/lv_draw_buf_convert_neon.c \
./src/draw/lv_draw_label.c \
./src/draw/dma2d/lv_draw_dma2d.c \
./src/draw/dma2d/lv_draw_dma2d_img.c \
./src/draw/dma2d/lv_draw_dma2d_fill.c \
./src/draw/eve/lv_draw_eve_fill.c \
./src/draw/eve/lv_draw_eve.c \
./src/draw/eve/lv_draw_eve_arc.c \
./src/draw/eve/lv_draw_eve_image.c \
./src/draw/eve/lv_draw_eve_ram_g.c \
./src/draw/eve/lv_draw_eve_triangle.c \
./src/draw/eve/lv_eve.c \
./src/draw/eve/lv_draw_eve_line.c \
./src/draw/eve/lv_draw_eve_letter.c \
./src/draw/renesas/dave2d/lv_draw_dave2d.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_image.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_triangle.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_mask_rectangle.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_utils.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_line.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_arc.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_label.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_fill.c \
./src/draw/renesas/dave2d/lv_draw_dave2d_border.c \
./src/draw/lv_draw_rect.c \
./src/draw/vg_lite/lv_vg_lite_path.c \
./src/draw/vg_lite/lv_vg_lite_stroke.c \
./src/draw/vg_lite/lv_draw_vg_lite_label.c \
./src/draw/vg_lite/lv_draw_vg_lite_img.c \
./src/draw/vg_lite/lv_draw_vg_lite_layer.c \
./src/draw/vg_lite/lv_draw_vg_lite_triangle.c \
./src/draw/vg_lite/lv_vg_lite_grad.c \
./src/draw/vg_lite/lv_draw_vg_lite_vector.c \
./src/draw/vg_lite/lv_draw_buf_vg_lite.c \
./src/draw/vg_lite/lv_draw_vg_lite_fill.c \
./src/draw/vg_lite/lv_vg_lite_math.c \
./src/draw/vg_lite/lv_vg_lite_utils.c \
./src/draw/vg_lite/lv_vg_lite_bitmap_font_cache.c \
./src/draw/vg_lite/lv_vg_lite_decoder.c \
./src/draw/vg_lite/lv_draw_vg_lite_arc.c \
./src/draw/vg_lite/lv_draw_vg_lite_mask_rect.c \
./src/draw/vg_lite/lv_draw_vg_lite_line.c \
./src/draw/vg_lite/lv_draw_vg_lite_box_shadow.c \
./src/draw/vg_lite/lv_draw_vg_lite.c \
./src/draw/vg_lite/lv_vg_lite_pending.c \
./src/draw/vg_lite/lv_draw_vg_lite_border.c \
./src/themes/mono/lv_theme_mono.c \
./src/themes/lv_theme.c \
./src/themes/simple/lv_theme_simple.c \
./src/themes/default/lv_theme_default.c \
./src/debugging/sysmon/lv_sysmon.c \
./src/debugging/monkey/lv_monkey.c \
./src/debugging/vg_lite_tvg/vg_lite_matrix.c \
./src/debugging/test/lv_test_indev_gesture.c \
./src/debugging/test/lv_test_indev.c \
./src/debugging/test/lv_test_fs.c \
./src/debugging/test/lv_test_screenshot_compare.c \
./src/debugging/test/lv_test_display.c \
./src/debugging/test/lv_test_helpers.c \
./src/display/lv_display.c \
./src/stdlib/clib/lv_mem_core_clib.c \
./src/stdlib/clib/lv_string_clib.c \
./src/stdlib/clib/lv_sprintf_clib.c \
./src/stdlib/rtthread/lv_string_rtthread.c \
./src/stdlib/rtthread/lv_sprintf_rtthread.c \
./src/stdlib/rtthread/lv_mem_core_rtthread.c \
./src/stdlib/builtin/lv_sprintf_builtin.c \
./src/stdlib/builtin/lv_tlsf.c \
./src/stdlib/builtin/lv_string_builtin.c \
./src/stdlib/builtin/lv_mem_core_builtin.c \
./src/stdlib/lv_mem.c \
./src/stdlib/micropython/lv_mem_core_micropython.c \
./src/stdlib/uefi/lv_mem_core_uefi.c \
./src/indev/lv_indev.c \
./src/indev/lv_indev_scroll.c \
./src/indev/lv_indev_gesture.c \
./src/indev/lv_gridnav.c \
./src/tick/lv_tick.c \
./examples/event/lv_example_event_click.c \
./examples/event/lv_example_event_draw.c \
./examples/event/lv_example_event_bubble.c \
./examples/event/lv_example_event_button.c \
./examples/event/lv_example_event_trickle.c \
./examples/event/lv_example_event_streak.c \
./examples/others/gridnav/lv_example_gridnav_2.c \
./examples/others/gridnav/lv_example_gridnav_3.c \
./examples/others/gridnav/lv_example_gridnav_4.c \
./examples/others/gridnav/lv_example_gridnav_1.c \
./examples/others/gridnav/lv_example_gridnav_5.c \
./examples/others/font_manager/lv_example_font_manager_2.c \
./examples/others/font_manager/lv_example_font_manager_1.c \
./examples/others/font_manager/lv_example_font_manager_3.c \
./examples/others/file_explorer/lv_example_file_explorer_2.c \
./examples/others/file_explorer/lv_example_file_explorer_3.c \
./examples/others/file_explorer/lv_example_file_explorer_1.c \
./examples/others/imgfont/lv_example_imgfont_1.c \
./examples/others/snapshot/lv_example_snapshot_1.c \
./examples/others/translation/lv_example_translation_2.c \
./examples/others/translation/lv_example_translation_1.c \
./examples/others/observer/lv_example_observer_6.c \
./examples/others/observer/lv_example_observer_7.c \
./examples/others/observer/lv_example_observer_1.c \
./examples/others/observer/lv_example_observer_4.c \
./examples/others/observer/lv_example_observer_3.c \
./examples/others/observer/lv_example_observer_5.c \
./examples/others/observer/lv_example_observer_2.c \
./examples/others/monkey/lv_example_monkey_3.c \
./examples/others/monkey/lv_example_monkey_1.c \
./examples/others/monkey/lv_example_monkey_2.c \
./examples/others/gestures/lv_example_gestures.c \
./examples/others/ime/lv_example_ime_pinyin_1.c \
./examples/others/ime/lv_example_ime_pinyin_2.c \
./examples/others/fragment/lv_example_fragment_1.c \
./examples/others/fragment/lv_example_fragment_2.c \
./examples/scroll/lv_example_scroll_9.c \
./examples/scroll/lv_example_scroll_7.c \
./examples/scroll/lv_example_scroll_8.c \
./examples/scroll/lv_example_scroll_4.c \
./examples/scroll/lv_example_scroll_3.c \
./examples/scroll/lv_example_scroll_6.c \
./examples/scroll/lv_example_scroll_2.c \
./examples/scroll/lv_example_scroll_5.c \
./examples/scroll/lv_example_scroll_1.c \
./examples/grad/lv_example_grad_3.c \
./examples/grad/lv_example_grad_2.c \
./examples/grad/lv_example_grad_4.c \
./examples/grad/lv_example_grad_1.c \
./examples/anim/lv_example_anim_1.c \
./examples/anim/lv_example_anim_3.c \
./examples/anim/lv_example_anim_4.c \
./examples/anim/lv_example_anim_2.c \
./examples/anim/lv_example_anim_timeline_1.c \
./examples/get_started/lv_example_get_started_2.c \
./examples/get_started/lv_example_get_started_3.c \
./examples/get_started/lv_example_get_started_4.c \
./examples/get_started/lv_example_get_started_1.c \
./examples/styles/lv_example_style_9.c \
./examples/styles/lv_example_style_7.c \
./examples/styles/lv_example_style_8.c \
./examples/styles/lv_example_style_3.c \
./examples/styles/lv_example_style_4.c \
./examples/styles/lv_example_style_17.c \
./examples/styles/lv_example_style_10.c \
./examples/styles/lv_example_style_16.c \
./examples/styles/lv_example_style_5.c \
./examples/styles/lv_example_style_21.c \
./examples/styles/lv_example_style_2.c \
./examples/styles/lv_example_style_20.c \
./examples/styles/lv_example_style_18.c \
./examples/styles/lv_example_style_6.c \
./examples/styles/lv_example_style_15.c \
./examples/styles/lv_example_style_11.c \
./examples/styles/lv_example_style_12.c \
./examples/styles/lv_example_style_19.c \
./examples/styles/lv_example_style_1.c \
./examples/styles/lv_example_style_14.c \
./examples/styles/lv_example_style_13.c \
./examples/porting/osal/lv_example_osal.c \
./examples/porting/lv_port_disp_template.c \
./examples/porting/lv_port_indev_template.c \
./examples/porting/lv_port_fs_template.c \
./examples/porting/lv_port_lcd_stm32_template.c \
./examples/libs/tjpgd/lv_example_tjpgd_1.c \
./examples/libs/qrcode/lv_example_qrcode_1.c \
./examples/libs/gltf/lv_example_gltf_2.c \
./examples/libs/gltf/lv_example_gltf_4.c \
./examples/libs/gltf/lv_example_gltf_3.c \
./examples/libs/gltf/lv_example_gltf_1.c \
./examples/libs/libwebp/lv_example_libwebp_1.c \
./examples/libs/ffmpeg/lv_example_ffmpeg_1.c \
./examples/libs/ffmpeg/lv_example_ffmpeg_2.c \
./examples/libs/bmp/lv_example_bmp_1.c \
./examples/libs/tiny_ttf/lv_example_tiny_ttf_3.c \
./examples/libs/tiny_ttf/lv_example_tiny_ttf_1.c \
./examples/libs/tiny_ttf/lv_example_tiny_ttf_2.c \
./examples/libs/tiny_ttf/ubuntu_font.c \
./examples/libs/gif/lv_example_gif_1.c \
./examples/libs/gif/img_bulb_gif.c \
./examples/libs/gstreamer/lv_example_gstreamer_1.c \
./examples/libs/barcode/lv_example_barcode_1.c \
./examples/libs/libjpeg_turbo/lv_example_libjpeg_turbo_1.c \
./examples/libs/libpng/img_png_demo.c \
./examples/libs/libpng/lv_example_libpng_1.c \
./examples/libs/lodepng/lv_example_lodepng_1.c \
./examples/libs/lodepng/img_wink_png.c \
./examples/libs/freetype/lv_example_freetype_1.c \
./examples/libs/freetype/lv_example_freetype_3.c \
./examples/libs/freetype/lv_example_freetype_2.c \
./examples/libs/rlottie/lv_example_rlottie_1.c \
./examples/libs/rlottie/lv_example_rlottie_approve.c \
./examples/libs/rlottie/lv_example_rlottie_2.c \
./examples/libs/svg/lv_example_svg_3.c \
./examples/libs/svg/lv_example_svg_1.c \
./examples/libs/svg/lv_example_svg_2.c \
./examples/layouts/grid/lv_example_grid_6.c \
./examples/layouts/grid/lv_example_grid_1.c \
./examples/layouts/grid/lv_example_grid_2.c \
./examples/layouts/grid/lv_example_grid_4.c \
./examples/layouts/grid/lv_example_grid_5.c \
./examples/layouts/grid/lv_example_grid_3.c \
./examples/layouts/flex/lv_example_flex_4.c \
./examples/layouts/flex/lv_example_flex_2.c \
./examples/layouts/flex/lv_example_flex_1.c \
./examples/layouts/flex/lv_example_flex_3.c \
./examples/layouts/flex/lv_example_flex_5.c \
./examples/layouts/flex/lv_example_flex_6.c \
./examples/widgets/obj/lv_example_obj_2.c \
./examples/widgets/obj/lv_example_obj_3.c \
./examples/widgets/obj/lv_example_obj_1.c \
./examples/widgets/arc/lv_example_arc_3.c \
./examples/widgets/arc/lv_example_arc_1.c \
./examples/widgets/arc/lv_example_arc_2.c \
./examples/widgets/tabview/lv_example_tabview_2.c \
./examples/widgets/tabview/lv_example_tabview_1.c \
./examples/widgets/label/lv_example_label_1.c \
./examples/widgets/label/lv_example_label_2.c \
./examples/widgets/label/lv_example_label_7.c \
./examples/widgets/label/lv_example_label_6.c \
./examples/widgets/label/lv_example_label_3.c \
./examples/widgets/label/lv_example_label_4.c \
./examples/widgets/label/lv_example_label_5.c \
./examples/widgets/arclabel/lv_example_arclabel_1.c \
./examples/widgets/canvas/lv_example_canvas_3.c \
./examples/widgets/canvas/lv_example_canvas_10.c \
./examples/widgets/canvas/lv_example_canvas_2.c \
./examples/widgets/canvas/lv_example_canvas_9.c \
./examples/widgets/canvas/lv_example_canvas_11.c \
./examples/widgets/canvas/lv_example_canvas_7.c \
./examples/widgets/canvas/lv_example_canvas_1.c \
./examples/widgets/canvas/lv_example_canvas_12.c \
./examples/widgets/canvas/lv_example_canvas_8.c \
./examples/widgets/canvas/lv_example_canvas_4.c \
./examples/widgets/canvas/lv_example_canvas_6.c \
./examples/widgets/canvas/lv_example_canvas_5.c \
./examples/widgets/switch/lv_example_switch_1.c \
./examples/widgets/switch/lv_example_switch_2.c \
./examples/widgets/image/lv_example_image_1.c \
./examples/widgets/image/lv_example_image_4.c \
./examples/widgets/image/lv_example_image_5.c \
./examples/widgets/image/lv_example_image_3.c \
./examples/widgets/image/lv_example_image_2.c \
./examples/widgets/spinner/lv_example_spinner_1.c \
./examples/widgets/menu/lv_example_menu_2.c \
./examples/widgets/menu/lv_example_menu_4.c \
./examples/widgets/menu/lv_example_menu_5.c \
./examples/widgets/menu/lv_example_menu_1.c \
./examples/widgets/menu/lv_example_menu_3.c \
./examples/widgets/calendar/lv_example_calendar_2.c \
./examples/widgets/calendar/lv_example_calendar_1.c \
./examples/widgets/list/lv_example_list_1.c \
./examples/widgets/list/lv_example_list_2.c \
./examples/widgets/checkbox/lv_example_checkbox_1.c \
./examples/widgets/checkbox/lv_example_checkbox_2.c \
./examples/widgets/win/lv_example_win_1.c \
./examples/widgets/dropdown/lv_example_dropdown_2.c \
./examples/widgets/dropdown/lv_example_dropdown_1.c \
./examples/widgets/dropdown/lv_example_dropdown_3.c \
./examples/widgets/keyboard/lv_example_keyboard_3.c \
./examples/widgets/keyboard/lv_example_keyboard_1.c \
./examples/widgets/keyboard/lv_example_keyboard_2.c \
./examples/widgets/lottie/lv_example_lottie_approve.c \
./examples/widgets/lottie/lv_example_lottie_2.c \
./examples/widgets/lottie/lv_example_lottie_1.c \
./examples/widgets/bar/lv_example_bar_3.c \
./examples/widgets/bar/lv_example_bar_7.c \
./examples/widgets/bar/lv_example_bar_4.c \
./examples/widgets/bar/lv_example_bar_5.c \
./examples/widgets/bar/lv_example_bar_1.c \
./examples/widgets/bar/lv_example_bar_2.c \
./examples/widgets/bar/lv_example_bar_6.c \
./examples/widgets/tileview/lv_example_tileview_1.c \
./examples/widgets/span/lv_example_span_1.c \
./examples/widgets/table/lv_example_table_1.c \
./examples/widgets/table/lv_example_table_2.c \
./examples/widgets/roller/lv_example_roller_2.c \
./examples/widgets/roller/lv_example_roller_1.c \
./examples/widgets/roller/lv_example_roller_3.c \
./examples/widgets/chart/lv_example_chart_2.c \
./examples/widgets/chart/lv_example_chart_7.c \
./examples/widgets/chart/lv_example_chart_3.c \
./examples/widgets/chart/lv_example_chart_8.c \
./examples/widgets/chart/lv_example_chart_4.c \
./examples/widgets/chart/lv_example_chart_6.c \
./examples/widgets/chart/lv_example_chart_1.c \
./examples/widgets/chart/lv_example_chart_5.c \
./examples/widgets/textarea/lv_example_textarea_1.c \
./examples/widgets/textarea/lv_example_textarea_4.c \
./examples/widgets/textarea/lv_example_textarea_2.c \
./examples/widgets/textarea/lv_example_textarea_3.c \
./examples/widgets/scale/lv_example_scale_1.c \
./examples/widgets/scale/lv_example_scale_6.c \
./examples/widgets/scale/lv_example_scale_5.c \
./examples/widgets/scale/lv_example_scale_9.c \
./examples/widgets/scale/lv_example_scale_4.c \
./examples/widgets/scale/lv_example_scale_8.c \
./examples/widgets/scale/lv_example_scale_2.c \
./examples/widgets/scale/lv_example_scale_12.c \
./examples/widgets/scale/lv_example_scale_3.c \
./examples/widgets/scale/lv_example_scale_10.c \
./examples/widgets/scale/lv_example_scale_11.c \
./examples/widgets/scale/lv_example_scale_7.c \
./examples/widgets/line/lv_example_line_1.c \
./examples/widgets/imagebutton/lv_example_imagebutton_1.c \
./examples/widgets/button/lv_example_button_3.c \
./examples/widgets/button/lv_example_button_2.c \
./examples/widgets/button/lv_example_button_1.c \
./examples/widgets/led/lv_example_led_1.c \
./examples/widgets/buttonmatrix/lv_example_buttonmatrix_1.c \
./examples/widgets/buttonmatrix/lv_example_buttonmatrix_3.c \
./examples/widgets/buttonmatrix/lv_example_buttonmatrix_2.c \
./examples/widgets/slider/lv_example_slider_2.c \
./examples/widgets/slider/lv_example_slider_4.c \
./examples/widgets/slider/lv_example_slider_1.c \
./examples/widgets/slider/lv_example_slider_3.c \
./examples/widgets/animimg/lv_example_animimg_1.c \
./examples/widgets/msgbox/lv_example_msgbox_3.c \
./examples/widgets/msgbox/lv_example_msgbox_2.c \
./examples/widgets/msgbox/lv_example_msgbox_1.c \
./examples/widgets/spinbox/lv_example_spinbox_1.c \
./examples/assets/img_multilang_like.c \
./examples/assets/img_skew_strip.c \
./examples/assets/animimg001.c \
./examples/assets/emoji/img_emoji_F617.c \
./examples/assets/img_star.c \
./examples/assets/animimg002.c \
./examples/assets/imgbtn_mid.c \
./examples/assets/imgbtn_right.c \
./examples/assets/imgbtn_left.c \
./examples/assets/img_svg_img.c \
./examples/assets/img_transform_avatar_15.c \
./examples/assets/img_cogwheel_indexed16.c \
./examples/assets/img_hand.c \
./examples/assets/img_cogwheel_argb.c \
./examples/assets/animimg003.c \
./examples/assets/img_caret_down.c \
./examples/assets/img_cogwheel_rgb.c
